import numpy as np
import tifffile
from skimage.filters import frangi
from skimage.morphology import skeletonize
import scipy.ndimage as ndi
import json
import os
from typing import Optional, List

def extract_skeletons_from_volume(volume_path: Optional[str] = None, chunk_size: int = 128) -> None:
    """
    Extracts SWC topological skeletons from a raw 3D intensity volume in an unsupervised manner.
    Uses Frangi Vesselness Filter + 3D Skeletonization.
    """
    spacing = [1.0, 1.0, 1.0] # Default spacing
    
    if os.path.exists("config.json"):
        with open("config.json", "r") as f:
            config = json.load(f)
            volume_path = volume_path or config.get("volume_path")
            spacing = config.get("spacing_xyz", spacing)
            
    volume_path = volume_path or "dummy.tif"
    print(f"Loading raw volume: {volume_path}")
    print(f"Using XYZ spacing (microns): {spacing}")
    try:
        vol = tifffile.imread(volume_path)
    except FileNotFoundError:
        print("Volume not found. Generating a dummy 3D volume (128x128x128) with a tube...")
        vol = np.zeros((128, 128, 128), dtype=np.float32)
        vol[30:100, 64, 64] = 255.0  # draw a tube
        vol = ndi.gaussian_filter(vol, sigma=2.0)
        vol += np.random.normal(0, 5, vol.shape)
        
    print(f"Volume Shape: {vol.shape}, Dtype: {vol.dtype}")
    
    # 1. Frangi Filter (Vesselness/Ridge detection)
    print("Applying 3D Frangi Filter (Ridge Detection)...")
    vesselness = frangi(vol, sigmas=range(1, 4, 1), alpha=0.5, beta=0.5, gamma=15)
    
    # 2. Thresholding the intensity mountain
    threshold = np.percentile(vesselness, 99)
    binary_vessels = vesselness > threshold
    
    print("Applying 3D Skeletonization...")
    # 3. 3D Skeletonization (Lee 1994)
    skeleton = skeletonize(binary_vessels)
    
    # 4. Group into distinct fragments and export to a single SWC
    labeled_skel, num_features = ndi.label(skeleton)
    print(f"Extracted {num_features} distinct skeleton fragments.")
    
    global_node_id = 1
    with open("extracted_fragments.swc", "w") as f:
        f.write("# SWC file generated by NeuroVLM Unsupervised Skeletonization\n")
        f.write("# id type x y z radius parent\n")
        
        for i in range(1, num_features + 1):
            z, y, x = np.where(labeled_skel == i)
            if len(z) == 0:
                continue
                
            for node_idx, (nz, ny, nx) in enumerate(zip(z, y, x)):
                parent = -1 if node_idx == 0 else global_node_id - 1
                
                # Scale by XYZ spacing (microns)
                real_x = nx * spacing[0]
                real_y = ny * spacing[1]
                real_z = nz * spacing[2]
                
                f.write(f"{global_node_id} 3 {real_x:.2f} {real_y:.2f} {real_z:.2f} 1.0 {parent}\n")
                global_node_id += 1
    
    tifffile.imwrite("dummy_vesselness.tif", vesselness.astype(np.float32))
    tifffile.imwrite("dummy_skeleton.tif", (skeleton * 255).astype(np.uint8))
    print("Saved dummy_vesselness.tif, dummy_skeleton.tif and extracted_fragments.swc")

if __name__ == "__main__":
    extract_skeletons_from_volume()
